<?php

namespace AdminVacacionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TipoPermisoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoPermisoRepository extends EntityRepository
{
    public function findAjax($value){
        return $this->getEntityManager()
        ->createQuery(
            'SELECT p FROM AdminVacacionBundle:TipoPermiso p WHERE p.nombre LIKE :value')
            ->setParameter('value','%'.$value.'%')
            ->getResult();
    }
}
