<?php

namespace AdminVacacionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VacacionModRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VacacionModRepository extends EntityRepository
{
}
