<?php

namespace AdminVacacionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VacacionDetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VacacionDetalleRepository extends EntityRepository
{
	public function deleteByVacacion($vacacion)
	{
		$em=$this->getEntityManager();

		$query=$em->createQuery('DELETE FROM AdminVacacionBundle:VacacionDetalle d where d.vacacionCabecera=:vacacion ')
			->setParameter('vacacion',$vacacion);

		$query->execute();
	}
}
