<?php

namespace AdminVacacionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VacacionGestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VacacionGestionRepository extends EntityRepository
{
	public function findByDiasDisponibles($empleado, $tipo)
	{
		$em = $this->getEntityManager();

		return $em->createQuery(
			'SELECT SUM(g.dias-g.tomados) as diasDisponibles
      FROM AdminVacacionBundle:vacacionGestion g
      WHERE g.empleado=:empleado 
      and g.dias>g.tomados 
      and g.estado=1
      and g.tipo=:tipo
      ')->setParameter('empleado', $empleado)->setParameter('tipo', $tipo)->getResult();
	}

	public function findVacacionGestionDisponibleByEmpleado($empleado, $tipo)
	{
		$em = $this->getEntityManager();
		return $em->createQuery(
			'SELECT g
      FROM AdminVacacionBundle:vacacionGestion g
      WHERE g.empleado=:empleado 
      and g.dias>g.tomados 
      and g.estado=1
      and g.tipo=:tipo
      ORDER BY g.gestion ASC
      ')->setParameter('empleado', $empleado)->setParameter('tipo', $tipo)->getResult();
	}

	public function findByGestionUtilizadas($gestion, $empleado)
	{//TRAE TODAS LAS GESTION A PARTIR DE LA GESTION ORDENADAS DE ASCENDENTE ESPECIFICADA EN EL REGISTRO DE LA VACACION DE CONFIGURACION
		$em = $this->getEntityManager();

		return $em->createQuery(
			'SELECT g 
			FROM AdminVacacionBundle:VacacionGestion g 
			WHERE g.gestion>=:gestion 
			and g.empleado=:empleado 
			order by g.gestion asc'
		)->setParameter('empleado', $empleado)
			->setParameter('gestion', $gestion)
			->getResult();
	}
}
