# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        AdminVacacionBundle\Entity\Usuario:
            algorithm:           md5
            encode_as_base64:    false
            iterations:          1

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        usuEmpAdm:
            entity: { class: AdminVacacionBundle\Entity\Usuario, property: login }

    firewalls:
          # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        EmpAdm:
             pattern: ^/emp/adm*
             anonymous: ~
             provider: usuEmpAdm
             form_login:
                 login_path: /emp/adm/seguridad/login
                 check_path: /emp/adm/seguridad/login_check
                 default_target_path: /emp/adm/
                 always_use_default_target_path: true
              # access_denied_url: /emp/adm/seguridad/login
             logout:
                 path: /emp/adm/seguridad/logout
                 target: /emp/adm/seguridad/login
            # activate different ways to authenticate
            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_control:
          - { path: ^/emp/adm/seguridad/login,       roles: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/emp/adm/$,                     roles: IS_AUTHENTICATED_FULLY }
          - { path: ^/emp/adm/vg/*,                  roles: [ROLE_EMPADM,IS_AUTHENTICATED_FULLY] }
          - { path: ^/emp/adm/f/*,                   roles: [ROLE_EMPADM,IS_AUTHENTICATED_FULLY] }
          - { path: ^/emp/adm/p/*,                   roles: [ROLE_EMPADM,IS_AUTHENTICATED_FULLY] }
          - { path: ^/emp/adm/vc/*,                   roles: [ROLE_EMPADM,IS_AUTHENTICATED_FULLY] }
          - { path: ^/emp/adm/s/*,                   roles: [ROLE_EMPADM,IS_AUTHENTICATED_FULLY] }
          - { path: ^/emp/adm/bajamedica/*,          roles: [ROLE_EMPPOR,IS_AUTHENTICATED_FULLY] }
          - { path: ^/emp/adm/reporte/*,          roles: [ROLE_EMPPOR,IS_AUTHENTICATED_FULLY] }
# - { path: ^/*,                            roles: IS_AUTHENTICATED_ANONYMOUSLY }
