services:
#    admin_vacacion.example:
#        class: AdminVacacionBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
     cps_user_utilitario:
          class: AdminVacacionBundle\Utilitarios\Utilitario