<?php

namespace UserVacacionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PermisoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PermisoAntRepository extends EntityRepository
{

}
