<?php

namespace Cps\Administracion\AdministracionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CentrocostoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CentrocostoRepository extends EntityRepository
{
	public function findAjaxValue($term){
        $em = $this->getEntityManager();
        $term = str_replace(' ', '%', $term);
        $consul = $em->createQuery('SELECT c FROM CpsAdministracionBundle:Centrocosto c
        							JOIN c.servicio s JOIN c.sucursal su
                                        WHERE c.servicio=s.id AND s.nombre LIKE \'%'.$term.'%\' OR su.nombre LIKE \'%'.$term.'%\'
                                 ');
        $resp = $consul->getResult();
        return $resp;
    }
}
