<?php

namespace Cps\Administracion\AdministracionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ServicioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServicioRepository extends EntityRepository
{
}
