<?php

namespace Cps\Personal\PlanillaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SueldoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SueldoRepository extends EntityRepository
{
}
